# Prezto
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Preferred zsh options
unsetopt correct_all

# Alias
alias lla='ls -lA'
alias ag=pt
alias diff='command diff'  # for Prezto

# ls on cd
chpwd() { ls }

# ~/bin
path=(~/bin(N-/) $path)

# golang
export GOPATH=$HOME

# homebrew
export PATH="/opt/homebrew/bin:$PATH"
export HOMEBREW_BREWFILE="$HOME/.brewfile"
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# asdf
. $(brew --prefix asdf)/asdf.sh

# Load .zshrc.local
[ -s ~/.zshrc.local ] && . ~/.zshrc.local
