# brew "docker" # https://docs.docker.com/docker-for-mac/apple-m1/
brew "asdf"
brew "gawk"
brew "gpg"
brew "jq"
brew "lesspipe"
brew "nkf"
brew "rcm"
brew "readline"
brew "sqlite"
brew "the_platinum_searcher"
brew "tig"
brew "tree"
brew "wget"
