cask "alfred"
cask "appcleaner"
cask "devdocs"
cask "dropbox"
cask "google-chrome"
cask "google-japanese-ime"
cask "gyazo"
cask "iterm2"
cask "steam"
cask "virtualbox"
cask "visual-studio-code"
cask "vivaldi"
cask "wercker"

brew "autoconf"
brew "docker-machine"
brew "docker"
brew "fzf"
brew "gdbm"
brew "gibo"
brew "git-lfs"
brew "git"
brew "go"
brew "icu4c"
brew "jq"
brew "libyaml"
brew "mozjpeg"
brew "nkf"
brew "node"
brew "nodebrew"
brew "oniguruma"
brew "openssl"
brew "openssl"
brew "optipng"
brew "pcre"
brew "peco"
brew "perl"
brew "pkg-config"
brew "python"
brew "rbenv-binstubs"
brew "rbenv"
brew "rcm"
brew "readline"
brew "ruby-build"
brew "ruby"
brew "sqlite"
brew "the_platinum_searcher"
brew "tig"
brew "tree"
brew "vim"
brew "wget"
brew "yarn"
brew "z"
brew "zsh"

mas "Pixelmator", id: 407963104
mas "CotEditor", id: 1024640650
mas "Bitwarden", id: 1352778147
