#!/bin/zsh
set -e
autoload -Uz colors
colors
cd `dirname $0`

function dotfiles_run_installers {
  local operation="$1"
  shift

  local -a installers
  if [ $# -gt 0 ]; then
    for command in $*; do
      source installers/*_$command.zsh
    done
  else
    for file in $(ls installers/*.zsh); do
      source $file
    done
  fi

  for installer in $installers; do
    echo "${fg[blue]}# ----------------------------------------${reset_color}"
    echo "${fg[blue]}# ${operation} ${fg[magenta]}${installer}${reset_color}"
    echo
    ${operation}_${installer}
    echo
  done
}

dotfiles_run_installers install $*
exec $SHELL -l
